### ISSUE TITLE
Loading game with special chars in the name will crash the program

### ISSUE THREAD

**Issue by towerwatchman** [KJNeko/Atlas#42] opened 2023-05-04 01:50 UTC
This can be replicated with most Non-ASCII Glyphs. See example below

![image](https://user-images.githubusercontent.com/2230446/236091247-16392c33-708c-4b7e-b62d-4b9fcdd420be.png)

![image](https://user-images.githubusercontent.com/2230446/236091318-848a046b-3f4b-434b-964d-1a1431ca0f79.png)

The path is indeed valid:

![image](https://user-images.githubusercontent.com/2230446/236091510-5bdfa90c-76cd-4a7d-8ad8-f90425829125.png)

**Comment by KJNeko** [comment] 2023-05-04 02:10
Problem is most likely going to be something to due with a conversion to string. Will require some runtime debugging to find out where it's choking.
https://en.cppreference.com/w/cpp/filesystem/path/u8path
Will have to look into how std::locale works

**Comment by towerwatchman** [comment] 2023-05-16 15:57
This appears to be fixed with last merge.

**Comment by KJNeko** [comment] 2023-05-23 18:20
Confirmed fix for linux. Not sure there was ever a problem. Will check windows next

**Comment by KJNeko** [comment] 2023-05-24 19:11
Issue has been fixed.

Turns out this entire reason was because Windows is a fucking trainwreck of an operating system.

In order to fix this issue. We had to add `-DUNICODE` to the GCC compiler flags. As well as bonking windows over the heat with a fucking brick and do `setlocale(LC_ALL, ".UTF8);` in main.cpp

Closing as through my short tests it seems to be fixed. Folders are properly made now with the correct names. If this issue shows up again open the issue again.

**Closed by KJNeko** 2023-05-24 19:11 UTC
Labels: bug, CRITICAL ISSUE, needs fix verification, fuck windows
